services:

  php:
    build: ./php
    ports:
      - 80:80
    volumes:
      - ../:/var/www/html
    working_dir: /var/www/html/public
    entrypoint: [ "php", "-S", "0.0.0.0:80" ]
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
#      MYSQL_USER: user
#      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: false
    ports:
      - 3306:3306